inventory:
  items:
    knockbakinator:
      slot: 0
      material: STICK
      name: "&aKnockBakinator"
      lore:
        - "&7Clicca per diverterti!"
    Profilo:
      slot: 1
      material: SKULL_ITEM
      name: "&bProfilo"
      lore:
        - "&bIl Tuo Profilo"
    Private:
      slot: 2
      material: ANVIL
      name: "&cBedwars Private"
      lore:
        - "&7Invita un amico!"
    Modalità:
      slot: 4
      material: NETHER_STAR
      name: "&eModalità"
      lore:
        - "&7Seleziona una modalità"
    Parkour:
      slot: 7
      material: LADDER
      name: "&cParkour"
      lore:
        - "&7Scopri il parkour"
    Giocatori:
      slot: 8
      material: LIGHT_BLUE_DYE
      name: "&aGiocatori Abilitati"
      lore:
        - "&7Attiva/disattiva i giocatori"
    Lobby:
      slot: 9
      material: BED
      name: "&cTorna alla Lobby"
      lore:
        - "&7Torna alla lobby"

lobby:
  spawn:
    world: world
    x: 0.5366884198678812
    y: 67.0
    z: 0.41076905839123434
    yaw: 0.0
    pitch: 0.0
