inventory:
  items:
    - id: 0
      material: STICK
      name: "&aKnockBakinator"
      lore:
        - "&7Clicca per diverterti!"
      unbreakable: true
      slot: 0
    - id: 1
      material: SKULL_ITEM
      data: 3
      name: "&bIl Tuo Profilo"
      lore:
        - "&7Clicca per vedere le tue statistiche"
      unbreakable: true
      slot: 1
    - id: 2
      material: ANVIL
      name: "&cBedwars Private"
      lore:
        - "&7Invita un amico!"
      unbreakable: true
      slot: 2
    - id: 4
      material: STAR
      name: "&eModalità"
      lore:
        - "&7Seleziona una modalità"
      unbreakable: true
      slot: 4
    - id: 6
      material: LADDER
      name: "&cParkour"
      lore:
        - "&7Scopri il parkour"
      unbreakable: true
      slot: 6
    - id: 7
      material: WOOL
      data: 11
      name: "&aGiocatori Abilitati"
      lore:
        - "&7Attiva/disattiva i giocatori"
      unbreakable: true
      slot: 7
    - id: 8
      material: BED
      name: "&cTorna alla Lobby"
      lore:
        - "&7Torna alla vera lobby"
      unbreakable: true
      slot: 8
