version: "1.0"
log-format: '[EverCensor] {player} ha scritto: {message}'
click-message: '/localmute {player} 1d Linguaggio scurrile -s'
censored-words:
  parola_inappropriata1: '***'
  parola_inappropriata2: '***'
