# EverCensor for EverCraft by salmone3O
# {player}, {server}, {message}
version: "1.0" # DO NOT CHANGE

log-format: '&b&lEC &7» &8[&7{server}&8] &c{player} ha scritto: &e{message}'
click-message: '/localmute {player} 1d Linguaggio scurrile -s'

hover-message:
  - '&bNome: &f{player}'
  - '&bServer: &f{server}'
  - '&bMessaggio: &f{message}'
  - ''
  - '&aClicca qui per mutare &b{player}'

censored-words:
  cazzo: 'c***o'
  merda: 'm***a'
  stronzo: 's*****o'
  porcodio: 'p******o'
  puttana: 'p******a'
  troia: 't****a'
  vaffanculo: 'v********o'
  fanculo: 'f*****o'
  minchia: 'm*****a'
  coglione: 'c******e'
  frocio: 'f****o'
  ricchione: 'r*******e'
  negr*: 'n****o'
  negr*: 'n****a'
  zoccola: 'z******a'
  bastardo: 'b*******o'
  diomerda: 'd*******a'
  madonna: 'm******a'
  dio: 'd**'
  porcamadonna: 'p**********a'
  porco: 'p****o'
  gesù: 'g***ù'
  cristo: 'c*****o'
  porno: 'p****o'
  sesso: 's****o'
  fica: 'f**a'
  fregna: 'f*****a'
  pipì: 'p***ì'
  cacca: 'c***a'
  pisello: 'p*****o'
